name: Build and Upload Binaries

on:
  push:
    branches: [ "feature/native-build" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    name: Build on ${{ matrix.os }}
    needs: create_release
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: 'github'
        settings-path: ${{ github.workspace }}
        cache: 'maven'
    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image-job-reports: 'true'
        set-java-home: 'false'
        cache: 'maven'
    - name: Build with Maven
      run: mvn clean -B verify -Pnative -Dimage_os=${{ matrix.os }} -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_name: maven-settings-decoder-${{ matrix.os }}
        asset_path: target/maven-settings-decoder-${{ matrix.os }}${{ matrix.os == 'windows' && '.exe' || '' }}
        asset_content_type: application/octet-stream
